os: osx
language: shell

install:
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install pyinstaller  # Install PyInstaller separately
  - hash -r  # Refresh the shell to recognize the new command

script:
  - pyinstaller --version  # Check PyInstaller version
  - pyinstaller --onefile main.py

after_success:
  - mkdir deploy
  - mv dist/main deploy/
  - hdiutil create -format UDZO -srcfolder deploy -ov -volname "Py-Clock" "Py-Clock.dmg"
